require 'pry'
require_relative '../lib/models/song'
require_relative '../lib/models/artist'
require_relative '../lib/models/genre'
require_relative '../lib/models/library_parser'
require_relative '../lib/models/sitegenerator.rb'
# require_relative '../lib/concerns/<FILES_HERE>'